### ISSUE TITLE
A suggestion, not an issue

### ISSUE THREAD

**Issue by tilleul** [fadden/fdraw#2]
I'm very impressed by all this work ! Thanks ! 30 years ago I would have played non-stop with your program !
Would it be hard to implement a XHPLOT feature ? HPLOT using XOR ...

Something else that would have been a killer back then is the ability to define sprites ...

Thanks for keeping all this and all the Apple II memories alive !

**Comment by fadden** [comment]
The XOR line draw mode is already there; see `&EXP 1` or `SetLineMode`.  This is used in the [hrfan demo](https://youtu.be/z2RFGVoaROE?t=3m6s).

**Comment by tilleul** [comment]
Sorry ! I completely overlooked that option ! Wonderful !
